services:
  db:
    build:
      context: ./build
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - /home/user/teledomophone/db_redis/volumes/postgresql/9.5/main:/var/lib/postgresql/data
    networks:
    - default

  redis:                                                                          
    image: redis
    ports:
    - "16379:6379" 
    restart: always
    networks:
    - default

version: '2.4'

networks:
  default:
    external: true 
    name: my_net
